services:
  qdrant:
    image: qdrant/qdrant:v1.15.1
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  agents:
    build: ./agents
    container_name: agents
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./agents/src:/app
    working_dir: /app
    depends_on:
      qdrant:
        condition: service_started

  indexing:
    build: ./indexing
    container_name: indexing
    env_file:
      - .env
    volumes:
      - ./indexing/src:/app
      - ./qdrant_storage:/qdrant/storage
    working_dir: /app
    command: tail -f /dev/null
    depends_on:
      qdrant:
        condition: service_started

volumes:
  qdrant_data: